### ISSUE TITLE
Hacer el verificador de sesiones

### ISSUE THREAD

**Issue by Carlos-V24** [Carlos-V24/Proyecto-PHP-BD-Seguridad-Web#2]
Se debera crear un codigo donde si tienes una sesion abierta o se pueda acceder a las paginas de registro de usuario o inicio de sesio, en cambio te debe redirigir a la pagina de inicio.

**Comment by AnaPau1603** [comment]
> Está también la hago yop

**Comment by AnaPau1603** [comment]
Listo :D
