### ISSUE TITLE
Menu de los productos

### ISSUE THREAD

**Issue by Carlos-V24** [Carlos-V24/Proyecto-PHP-BD-Seguridad-Web#4]
Deberas hacer una pagina donde se pueda mostrar todos los alimentos disponibles para comprar atraves de iteraciones y conexiones con la base de datos, mostrando imagen del producto, nombre, precio y un boton de agregar.

**Comment by AnaPau1603** [comment]
> Comenzaré con esta :)

**Comment by Carlos-V24** [comment]
Ok
